### ISSUE TITLE
Use `n-logger` for logging 

### ISSUE THREAD

**Issue by adambraimbridge** [financial-times-sandbox/tako#29] opened 2018-10-16 13:49 UTC
There's a [logger built into probot](https://github.com/probot/probot/blob/master/src/logger.ts), but it doesn't send logs to splunk. `n-logger` does. 

![image](https://user-images.githubusercontent.com/224547/47021151-cc4e3100-d152-11e8-8952-2f0608f9cb1e.png)

**Comment by simonplend** [comment] 2018-10-16 13:53
Related: #5.

**Comment by sjparkinson** [comment] 2018-10-30 18:19
Closing as duplicate of #5.

**Closed by sjparkinson** 2018-10-30 18:19 UTC
